# Generated by Django 3.0.1 on 2020-01-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user_id',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
