# Generated by Django 3.0.1 on 2020-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
